(function(){function search(it
/**/) {
var out='<!doctype html><html><head><meta name="viewport" content="width=device-width"><title>ansble: rest api-ed data store for you and your apps</title><link href="/built/css/main.css" rel="stylesheet"></head><body><nav class="header"><h1 class="header__logo">ansble</h1><ul class="header__nav"><li><a href="/" class="header__nav__item">home</a></li><li><a href="/about" class="header__nav__item">about</a></li><li><a href="/api" class="header__nav__item">api</a></li><li><a href="/docs" class="header__nav__item">docs</a></li></ul></nav><article class="article"><h2 class="article__heading">Search Results: '+( it.query )+'</h2>';var arr1=it.matches;if(arr1){var value,index=-1,l1=arr1.length-1;while(index<l1){value=arr1[index+=1];out+='<section class="search__result"><h3 class="search__result__heading"><a href="/'+( value.id )+'">'+( value.title )+'</a></h3><span class="search__meta">Published: '+( value.publishedDate )+'</span><p class="search__blurb">'+( value.content.slice(0, 200) )+'&hellip; [<a href="/'+( value.id )+'">more</a>]</p></section>';} } out+='</article><footer class="footer"><section class="footer__nav--copyright">&copy; 2015 ansble llc</section><section class="footer__nav__api"><a href="/api" class="footer__nav__link">api</a></section></footer><script src="/components/signup/signup.js"></script><script src="/templates"></script></body></html>';return out;
}var itself=search, _encodeHTML=(function (doNotSkipEncoded) {
		var encodeHTMLRules = { "&": "&#38;", "<": "&#60;", ">": "&#62;", '"': "&#34;", "'": "&#39;", "/": "&#47;" },
			matchHTML = doNotSkipEncoded ? /[&<>"'\/]/g : /&(?!#?\w+;)|<|>|"|'|\//g;
		return function(code) {
			return code ? code.toString().replace(matchHTML, function(m) {return encodeHTMLRules[m] || m;}) : "";
		};
	}());if(typeof module!=='undefined' && module.exports) module.exports=itself;else if(typeof define==='function')define(function(){return itself;});else {window.render=window.render||{};window.render['search']=itself;}}());